apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
  namespace: myapp-dev
  labels:
    app: myapp
    environment: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  
  # Replica limits
  minReplicas: 2 
  maxReplicas: 10   
  

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5min before scaling down
      policies:
      - type: Percent
        value: 50      # Scale down max 50% of current pods
        periodSeconds: 60
      - type: Pods
        value: 2       # Or max 2 pods at a time
        periodSeconds: 60
      selectPolicy: Min  # Choose the slower option
    
    scaleUp:
      stabilizationWindowSeconds: 0 
      policies:
      - type: Percent
        value: 100     # Can double pod count
        periodSeconds: 15
      - type: Pods
        value: 4       # Or add 4 pods at a time
        periodSeconds: 15
      selectPolicy: Max  # Choose the faster option
  
  # Metrics to scale on
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scale when avg CPU > 70%
  
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # Scale when avg memory > 80%